import Foundation

public enum SettingsFieldHelp {
    private static let descriptions: [String: String] = [
        "AD Mode": "Off disables detection. Color Uniqueness looks for unusual colors; Target Colors looks for selected color families; Infrared looks for thermal contrast. Detector settings last for this app session; startup returns AD to Off.",
        "Realtime Defaults": "Reset restores the detector settings to the realtime defaults for the selected mode.",
        "Motion": "On includes motion evidence in anomaly detection. Off disables the motion detector. Camera movement compensation is controlled by Registration and Movement Estimator.",
        "Saliency": "On enables the saliency detector, which looks for regions that stand out from their surroundings. Off disables it.",
        "Show Guide Boxes": "On shows cyan outlines for the centered scan zone and maximum small-target size. Off hides these guides.",
        "Show Hottest Region": "On draws a red ring around the hottest region as an infrared debugging aid. Off hides the ring.",
        "Show Candidate Blobs": "On displays candidate regions to help inspect detector behavior. Candidates are not necessarily confirmed detections. Off hides these overlays.",
        "Troubleshooting Debug": "On adds detailed anomaly frame and region information to application diagnostics. Use when investigating detector behavior; Off reduces diagnostic detail.",
        "Target Colors": "Choose the color families the Target Colors detector should look for. Multiple colors may be selected. A selected color is a search cue, not an identification.",
        "Person Relevance": "Controls how person-related evidence is used. Assist is experimental. This is a search aid, not confirmation that a detected object is a person.",
        "Sensitivity": "Controls how readily an outlier becomes a candidate. Lower values are stricter. Allowed: 0–100%.",
        "Motion Evidence": "Higher values strengthen motion evidence and its influence in combined anomaly scoring. Allowed: 0–100%.",
        "Scan Zone": "Centered portion of the frame scanned for anomalies. Lower values ignore more of the outer frame. Allowed: 50–100%.",
        "Min Hits": "Consecutive analyzed-frame hits in roughly the same motion-stabilized region required before promoting a detection. Allowed: 1–5.",
        "Color Candidates": "Maximum number of candidates retained by color detection. Allowed: 1–4.",
        "Stride": "Fixed analyzes at the selected frame interval. Adaptive adjusts the interval within the minimum frame count and maximum time settings.",
        "Frame Stride": "Analyze every Nth frame. Higher values reduce processing load but may miss brief motion. Allowed: 1–33 frames. Fixed uses this interval; Adaptive adjusts its cadence.",
        "Adaptive Minimum": "Minimum frame interval for adaptive analysis. Allowed here: 2–33 frames.",
        "Adaptive Maximum": "Maximum time interval for adaptive analysis. Allowed: 0.1–10 seconds.",
        "Detail": "Pixel sampling step for appearance analysis. Auto chooses from frame size; smaller steps inspect more detail at higher processing cost. Choices: Auto (0), or 1–4 pixels.",
        "Registration": "Compensates for camera motion. Affine usually follows camera movement more accurately; GMV is simpler and may use less processing.",
        "Movement Estimator": "Legacy uses the existing motion estimate. Shadow computes layered parallax diagnostics without changing detections. Active applies experimental layered parallax suppression.",
        "Infrared Palette": "Choose White Hot when brighter pixels are hotter, or Black Hot when darker pixels are hotter. Match the camera palette.",
        "Thermal Min Delta": "Minimum infrared pixel contrast before thermal or saliency evidence is considered. Higher values ignore weaker differences. Allowed: 1–64 intensity levels; these are not temperature degrees.",
        "Small Target Scale": "Maximum small-target box size as a fraction of the screen diagonal. Larger targets are down-ranked and may disappear as you zoom in. Allowed: 0.0015–0.03 of the diagonal, displayed as a reciprocal.",
        "Map layer": "Selects the background map shown in Map Pane. Available detail depends on the source and cached tiles. Contours is a separate overlay.",
        "Contours": "On adds elevation contour lines over the selected background map. Off hides them. Available detail depends on cached or available contour tiles.",
        "Follow Focused Drone": "On keeps Map Pane centered on the focused drone as telemetry arrives. Off lets you keep the map at the area you choose. This does not control recording or publishing.",
        "Max Cache Size": "Maximum map and terrain cache allowance in decimal gigabytes. Allowed: 0.1–1,000 GB. A smaller allowance may cause older cached data to be removed during maintenance; available storage can limit downloads.",
        "Maximum Tile Age": "Maximum retention age for cached tiles. Allowed: 1–3,650 whole days. Older tiles may be removed during cache maintenance, so retaining offline coverage may require downloading again.",
        "Auto Remove Bad Tiles": "On automatically removes encountered tiles matching quarantined bad-tile hashes. Off disables automatic removal. Long-press an incorrect tile to remove it and optionally quarantine matching tiles.",
        "FAA proxy": "Shows whether organization-provided access for NOTAM/TFR lookup is configured. Import your organization enrollment QR code to configure it. This is independent of personal CalTopo sign-in.",
        "Organization designator": "Short organization label used in aircraft mappings and operational metadata. Enter your organization’s chosen text. This does not sign you in or grant organization access.",
        "CalTopo track folder": "Name of the CalTopo folder used to organize published drone tracks. Enter a folder name; the app creates or reuses it on the selected map.",
        "Incident": "Incident name or identifier included in operational defaults. Free text; it does not select a CalTopo map.",
        "Operational period": "Label for the current operational period, such as a date or shift. Free text; this does not schedule recording.",
        "Team ID": "CalTopo Teams account identifier. Only needed for Teams API access. Enter Team ID, Credential ID, and Credential secret together, or leave them all blank for personal sign-in.",
        "Credential ID": "Identifier for a CalTopo Teams API credential. Copy it exactly from the Teams configuration. It is not your personal CalTopo username. Leave blank when using personal sign-in.",
        "Credential secret": "Secret associated with the CalTopo Teams Credential ID. Copy the complete value exactly; it is not your CalTopo password. Leave blank for personal sign-in. The value is hidden while editing.",
        "Connect Key": "Routing key used for CalTopo LiveTrack position reports. Use the value supplied for your setup; when blank, the app uses DRONE. It is not your personal CalTopo password.",
        "Domain": "CalTopo server hostname, optionally followed by a port, such as caltopo.com. Do not enter a map URL or path. Personal login uses caltopo.com.",
        "Map ID": "Identifier of the destination CalTopo map. Selecting a map in the browser fills this automatically. A Map ID alone does not grant access; use personal sign-in or valid Teams credentials.",
        "Device Name": "Name identifying this tablet in map markers, Map Folders, tracker coordination, and local track metadata. Enter a recognizable name. An organization-assigned name is read-only here.",
        "Tracker URL": "Base URL of your r2c-tracker server. Use the address supplied by your administrator, normally beginning with https://. The tracker is separate from CalTopo personal sign-in.",
        "Tracker API key": "Credential supplied by your r2c-tracker administrator or enrollment QR code. Copy it exactly. This is not a CalTopo credential and is not required for personal-map access.",
        "Enable live CalTopo publishing": "Allows the app to publish to the selected CalTopo map. Requires an authorized personal session or Teams credentials, a selected map, and flight confirmation for tracks. Turning this on does not confirm a drone or publish earlier flights automatically.",
        "Restrict media server access": "Accepts controller RTMP streams while blocking direct media-server viewing from other devices. Local playback, recording, and authorized R2C sharing remain available. Turn off only for trusted local viewers. Changing this setting restarts video.",
        "Capture Streams": "Records incoming video streams into local flight storage. On records video; Off leaves incoming video available without recording it. Changing this setting restarts the media server.",
        "Remote Video Control": "When enabled, an authenticated requester can choose video quality after the link test without a separate approval for each request. This does not grant access to unauthenticated viewers.",
        "Thumbnail & LiveTrack update interval": "Minimum time between thumbnail refreshes and LiveTrack updates. Allowed: 0.5–60 seconds; default: 5 seconds. Lower values use more battery and data.",
        "Bridge audio warnings": "Enables spoken or audible warnings for the Remote ID bridge. Muting lasts for the current app session; warnings are enabled again when the app starts.",
        "Use tracker peers": "Shares aircraft coordination with other devices through r2c-tracker when an incident map is selected. Requires tracker configuration. Standalone flights remain independent; this does not control personal CalTopo sign-in.",
        "Wi-Fi RID scanning": "Receives Remote ID over supported Wi-Fi hardware in addition to other enabled receivers. Availability depends on Android hardware and permissions.",
        "Proximity alerts": "Enables optional aircraft proximity warnings from received telemetry after accepting the notice. Off disables these warnings. Missing or delayed telemetry can prevent an alert; this is not proof that airspace is clear.",
        "Alert scope": "Published only checks pairs involving an aircraft claimed by this tablet. All aircraft checks any received pair, including ignored or unconfirmed aircraft. This does not change recording or publishing.",
        "Proximity spacing": "Separation threshold used by proximity alerts, in feet. Minimum 50 feet; default 100 feet.",
        "Min Dist": "Minimum movement, in feet, before another track point is recorded. Smaller values retain more detail and may retain more position noise. Minimum 2 feet.",
        "New Track Delay": "Gap between aircraft waypoints after which the current track ends and a later observation starts a new track. Measured in seconds; this is not a delay before publishing.",
        "Minimum Location Accuracy": "Required reported horizontal accuracy for RID positions. Choices: 30 m, 10 m, 3 m, or 1 m. Less accurate positions remain signal-only and are not added to the track.",
        "Bridge Check Distance": "Distance used by signal-loss warnings to distinguish an aircraft near the tablet from one that has moved away. Warnings are armed after the aircraft moves beyond this distance and suppressed when it returns near the tablet. Minimum 1 foot; default 20 feet. This is separate from proximity-alert spacing.",
        "Max Idle Time": "Minutes without qualifying RID activity or user interaction before the app closes automatically. Use 0 to disable automatic closing. Enter a nonnegative whole number.",
        "Audio Alarm Volume": "App alarm volume from 0% (silent) to 100%. The slider moves in 5% steps. Use Audio Alarm Test to check the current device output.",
        "Enable FAA Facility Map / LAANC lookup": "Looks up FAA UAS Facility Map information near the operating location. This is informational and does not request or grant an airspace authorization.",
        "Refresh controlled airspace automatically": "Automatically refreshes controlled-airspace information while its lookup feature is enabled. Off stops automatic refreshes.",
        "Enable nearby NOTAM / TFR monitoring": "Checks nearby NOTAMs and temporary flight restrictions through the configured FAA proxy. Requires organization-provided proxy access.",
        "Show NOTAMs on map": "Displays available NOTAM overlays on the map. Hiding the overlay does not change the restriction or grant permission to fly.",
        "Refresh automatically": "Periodically updates nearby NOTAM/TFR information while monitoring is enabled. Requires a connection and configured proxy access.",
        "NOTAM radius": "Search distance around the operating location, in statute miles. Larger areas may return more notices.",
        "Refresh interval": "Time between automatic NOTAM/TFR refreshes. Choices: 30 or 60 minutes.",
        "Enable protected-land checks": "Checks supported agency boundaries and land-use restrictions near the operating area. These are separate from FAA airspace restrictions.",
        "Show protected lands on map": "Displays supported protected-land boundaries on the map. Available when protected-land checks are enabled.",
        "Refresh protected lands automatically": "Automatically refreshes protected-land boundary information while checks are enabled. Requires network access for uncached data.",
        "Boundary query radius": "Search radius for protected-land boundaries in statute miles. Allowed: 1–50.",
        "Mode": "External display behavior. Off leaves it unmanaged; OS mirroring uses system display controls; App-managed presents a separate RID2Caltopo layout.",
        "Content": "Layout shown on an app-managed external display. Choices: Streams Grid, Map Only, Split: Streams + Map, or Observer Mode. This does not change the tablet’s main view.",
        "Alert routing": "Chooses where alerts appear when an external display is connected. Choices: Phone only (this device), External display only, or Both.",
        "Open automatically when connected": "Automatically opens the app-managed external view when a display connects. Off requires opening it manually.",
        "Allow interaction": "Allows supported input on the app-managed external display. Off makes that view display-only.",
        "Return to phone-only layout on disconnect": "Restores the single-device layout when an external display disconnects.",
        "Latitude, longitude": "Temporary location override for testing. Enter decimal latitude, then longitude, separated by a comma. Latitude: -90 to 90; longitude: -180 to 180.",
        "Recent days": "Number of recent days included in the diagnostic collection. Allowed: 1–30.",
        "Max Size (GB)": "Storage limit in gigabytes for this cleanup rule. Allowed: 0.1–1,000 GB.",
        "Max Age (days)": "Maximum age in days for this cleanup rule. Allowed: 1–3,650 whole days.",
        "Active profile": "The selected CalTopo credential source. Personal uses your browser sign-in; Teams uses installed team credentials. This is separate from the destination map.",
        "Connected Map": "The selected CalTopo destination. Tracks require flight confirmation; earlier flights awaiting a map require a publication choice.",
        "Domain and port": "CalTopo server hostname, optionally followed by a port, such as caltopo.com. Do not enter a map URL or path. Personal login uses caltopo.com.",
        "Min Dist (ft)": "Minimum movement, in feet, before another track point is recorded. Smaller values retain more detail and may retain more position noise. Minimum 2 feet.",
        "New Track Delay (s)": "Gap between aircraft waypoints after which the current track ends and a later observation starts a new track. Measured in seconds; this is not a delay before publishing.",
        "Max Idle Time (minutes)": "Minutes without qualifying RID activity or user interaction before the app closes automatically. Use 0 to disable automatic closing. Enter a nonnegative whole number.",
        "Bridge Check Distance (ft)": "Distance used by signal-loss warnings to distinguish an aircraft near the tablet from one that has moved away. Warnings are armed after the aircraft moves beyond this distance and suppressed when it returns near the tablet. Minimum 1 foot; default 20 feet. This is separate from proximity-alert spacing.",
        "Proximity Alert Spacing (ft, minimum 50; default 100)": "Separation threshold used by proximity alerts, in feet. Minimum 50 feet; default 100 feet.",
        "NOTAM radius (statute miles)": "Search distance around the operating location, in statute miles. Larger areas may return more notices.",
        "Refresh interval (seconds, minimum 1800)": "Time between automatic NOTAM/TFR refreshes. Choices: 30 or 60 minutes.",
        "Boundary query radius (statute miles)": "Search radius for protected-land boundaries in statute miles. Allowed: 1–50.",
        "FAA monitoring": "Checks nearby NOTAMs and temporary flight restrictions through the configured FAA proxy. Requires organization-provided proxy access.",
        "External display mode": "External display behavior. Off leaves it unmanaged; OS mirroring uses system display controls; App-managed presents a separate RID2Caltopo layout.",
        "Auto-open on connect": "Automatically opens the app-managed external view when a display connects. Off requires opening it manually.",
        "Allow external display interaction": "Allows supported input on the app-managed external display. Off makes that view display-only.",
    ]
    public static func description(for title: String) -> String {
        let key = title.components(separatedBy: ":").first ?? title
        return descriptions[key] ?? "Choose a value using this control. The available choices are shown in Settings."
    }
}
